AllCops:
  Exclude:
    - db/schema.rb
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'bin/*'

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Metrics/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
