name: Update Data files

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 5 * * 1,5'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: "!contains(github.event.head_commit.message, '[nodoc]')"
    steps:
    - uses: actions/checkout@master

    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1

    - uses: actions/cache@v1.1.2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    
    - name: Build Environment
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Update Data
      run: |
        bundle exec rake update_data:github_pull_requests
    - name: Commit files
      run: |
        git config --local user.email "github-actions@example.com"
        git config --local user.name "GitHub Actions"
        git commit -am "[nodoc] Updating Data files" || echo "No changes to commit"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
