name: Update Data files

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 5 * * 1,5'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: "!contains(github.event.head_commit.message, '[nodoc]')"
    steps:
    - uses: actions/checkout@master

    - name: Set up Ruby 3.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true

    - name: Update Data
      run: |
        bundle exec rake update_data:github_pull_requests
    - name: Commit files
      run: |
        git config --local user.email "github-actions@example.com"
        git config --local user.name "GitHub Actions"
        git commit -am "[nodoc] Updating Data files" || echo "No changes to commit"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
